### PR TITLE
TO-871: CircleCi config to deploy to aws-staging from develop branch

### PR DESCRIPTION
**Pull request by daimesava**

### CODE REVIEW

**Comment by jparklev** [comment]
would it be possible to have it deploy from master instead?

**Comment by levity** [comment]
Hey @jparklev the idea here is to deploy from both develop and master to aws, like we do for the migration dashboard. It’s a little redundant but has the advantage of allowing us to check our aws deployment process frequently

**Comment by daimesava** [comment]
@levity and @jparklev updated PR to deploy to the production AWS environment in parallel with now from master. That way we can switch hosting seamlessly

**Comment by jparklev** [comment]
awesome :D taking a quick look, do we need to add `deploy_aws_prod` to the list of `jobs` down at the bottom of the config as well?

**Comment by daimesava** [comment]
> do we need to add `deploy_aws_prod` to the list of `jobs` down at the bottom of the config as well?

yes :)
fixed in bf1892d

**Comment by jparklev** [comment]
>  updated PR to deploy to the production AWS environment in parallel with now from master. That way we can switch hosting seamlessly

quick follow up on this, what's the plan for this switch? are we already pointing vote.makerdao to the aws prod deployment?

**Comment by daimesava** [comment]
Not yet, but switch is seamless and we can do it anytime. 

Do you have apreferred window?

**Comment by jparklev** [comment]
sweet! would this Wednesday (4/1) morning eastern time work? maybe b/w 15:00 and 20:00 UTC?

**Comment by daimesava** [comment]
Works perfect. Lets sync up in chat

**Pull request merged**
